zookeeper:
  hosts:
    ec2-3-88-159-135.compute-1.amazonaws.com:
    # ip-172-31-37-15.us-east-2.compute.internal:
    # ip-172-31-34-231.us-east-2.compute.internal:

kafka_broker:
  hosts:
    ec2-3-88-159-135.compute-1.amazonaws.com:
    # ip-172-31-34-247.us-east-2.compute.internal:
    # ip-172-31-34-248.us-east-2.compute.internal:

control_center:
  hosts:
    ec2-3-88-159-135.compute-1.amazonaws.com:

all:
  vars:
    installation_method: archive
    confluent_archive_file_source: /home/ec2-user/confluent-7.7.7.tar.gz
    confluent_archive_file_remote: false
    ansible_connection: ssh
#    ansible_user: ec2-user
    ansible_become: false
#    ansible_ssh_private_key_file: /home/ec2-user/cp-ansible/certs/ssh_priv.pem
